-- class_batch.code and receipt.code are generated by (facilityId, year) counters,
-- so the uniqueness constraint must be per-facility, not global.
-- Existing data is trivially safe: all current rows belong to one facility,
-- so the composite constraint is already satisfied.

-- ClassBatch: drop global unique, add per-facility composite unique
DROP INDEX IF EXISTS "class_batch_code_key";
ALTER TABLE "class_batch" DROP CONSTRAINT IF EXISTS "class_batch_code_key";
CREATE UNIQUE INDEX "class_batch_facility_id_code_key" ON "class_batch"("facility_id", "code");

-- Receipt: drop global unique, add per-facility composite unique
DROP INDEX IF EXISTS "receipt_code_key";
ALTER TABLE "receipt" DROP CONSTRAINT IF EXISTS "receipt_code_key";
CREATE UNIQUE INDEX "receipt_facility_id_code_key" ON "receipt"("facility_id", "code");
