import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { withRls, SUPER, uniq } from './helpers.js';

/**
 * Facility-scoped code uniqueness invariant.
 *
 * ClassBatch.code and Receipt.code are generated by counters keyed (facilityId, year).
 * The DB constraint must be @@unique([facilityId, code]), NOT a global @unique.
 *
 * Invariant:
 *   - Two DIFFERENT facilities CAN both have the same code value (e.g. B-2026-0001).
 *   - The SAME facility CANNOT have two rows with the same code.
 */
describe('facility-scoped code uniqueness (ClassBatch + Receipt)', () => {
  const FACILITY_A = 1; // HQ (seeded)
  const SHARED_CODE_BATCH = 'B-3998-0001';
  const SHARED_CODE_RECEIPT = 'PT-3998-0001';

  let facilityBId: number;
  let courseId: string;

  // Track IDs for cleanup
  const created = {
    facilityIds: [] as number[],
    courseIds: [] as string[],
    batchIds: [] as string[],
    receiptIds: [] as string[],
  };

  beforeAll(async () => {
    await withRls(SUPER, async (tx) => {
      // Create a second facility so we can verify cross-facility code reuse
      const facilityB = await tx.facility.create({
        data: { code: uniq('FAC_B'), name: 'Facility B (test)', isActive: false },
      });
      facilityBId = facilityB.id;
      created.facilityIds.push(facilityBId);

      // Shared course (global — no facilityId on Course)
      const course = await tx.course.create({
        data: { code: uniq('CRS_FCODU'), name: 'Facility-code uniqueness test course', program: 'UCREA' },
      });
      courseId = course.id;
      created.courseIds.push(courseId);
    });
  });

  afterAll(async () => {
    await withRls(SUPER, async (tx) => {
      if (created.receiptIds.length > 0)
        await tx.receipt.deleteMany({ where: { id: { in: created.receiptIds } } });
      if (created.batchIds.length > 0)
        await tx.classBatch.deleteMany({ where: { id: { in: created.batchIds } } });
      if (created.courseIds.length > 0)
        await tx.course.deleteMany({ where: { id: { in: created.courseIds } } });
      if (created.facilityIds.length > 0)
        await tx.facility.deleteMany({ where: { id: { in: created.facilityIds } } });
    });
  });

  // ── ClassBatch ──────────────────────────────────────────────────────────────

  it('ClassBatch: two different facilities can share the same code', async () => {
    // Facility A creates a batch with the shared code
    const batchA = await withRls(SUPER, (tx) =>
      tx.classBatch.create({
        data: { facilityId: FACILITY_A, code: SHARED_CODE_BATCH, courseId, name: 'Batch A' },
      }),
    );
    expect(batchA.id).toBeTruthy();
    created.batchIds.push(batchA.id);

    // Facility B creates a batch with the SAME code — must succeed (different facility)
    const batchB = await withRls(SUPER, (tx) =>
      tx.classBatch.create({
        data: { facilityId: facilityBId, code: SHARED_CODE_BATCH, courseId, name: 'Batch B' },
      }),
    );
    expect(batchB.id).toBeTruthy();
    created.batchIds.push(batchB.id);

    expect(batchA.code).toBe(batchB.code);
    expect(batchA.facilityId).not.toBe(batchB.facilityId);
  });

  it('ClassBatch: same facility cannot have two rows with the same code', async () => {
    // Facility A already has SHARED_CODE_BATCH from the previous test; try a duplicate
    await expect(
      withRls(SUPER, (tx) =>
        tx.classBatch.create({
          data: {
            facilityId: FACILITY_A,
            code: SHARED_CODE_BATCH,
            courseId,
            name: 'Duplicate in facility A',
          },
        }),
      ),
    ).rejects.toThrow(); // Prisma throws on unique constraint violation
  });

  // ── Receipt ─────────────────────────────────────────────────────────────────

  it('Receipt: two different facilities can share the same code', async () => {
    const base = {
      courseId,
      yearsPrepaid: 1,
      annualPrice: 10_000_000,
      grossAmount: 10_000_000,
      tierPercent: 0,
      voucherPercent: 0,
      effectiveDiscountPercent: 0,
      netAmount: 10_000_000,
    };

    const receiptA = await withRls(SUPER, (tx) =>
      tx.receipt.create({
        data: { ...base, facilityId: FACILITY_A, code: SHARED_CODE_RECEIPT },
      }),
    );
    expect(receiptA.id).toBeTruthy();
    created.receiptIds.push(receiptA.id);

    // Facility B creates a receipt with the SAME code — must succeed (different facility)
    const receiptB = await withRls(SUPER, (tx) =>
      tx.receipt.create({
        data: { ...base, facilityId: facilityBId, code: SHARED_CODE_RECEIPT },
      }),
    );
    expect(receiptB.id).toBeTruthy();
    created.receiptIds.push(receiptB.id);

    expect(receiptA.code).toBe(receiptB.code);
    expect(receiptA.facilityId).not.toBe(receiptB.facilityId);
  });

  it('Receipt: same facility cannot have two rows with the same code', async () => {
    const base = {
      courseId,
      yearsPrepaid: 1,
      annualPrice: 10_000_000,
      grossAmount: 10_000_000,
      tierPercent: 0,
      voucherPercent: 0,
      effectiveDiscountPercent: 0,
      netAmount: 10_000_000,
    };

    // Facility A already has SHARED_CODE_RECEIPT from the previous test; try a duplicate
    await expect(
      withRls(SUPER, (tx) =>
        tx.receipt.create({
          data: { ...base, facilityId: FACILITY_A, code: SHARED_CODE_RECEIPT },
        }),
      ),
    ).rejects.toThrow(); // Prisma throws on unique constraint violation
  });
});
